all: false
template: testify
formatter: goimports
log-level: info
filename: "mock_{{.InterfaceName}}.go"
pkgname: mocks
structname: "Mock{{.InterfaceName}}"
packages:
  github.com/aleksejmetlusko/second-brain/internal/port/in:
    config:
      dir: "internal/port/in/mocks"
    interfaces:
      IngestDumpUseCase:
  github.com/aleksejmetlusko/second-brain/internal/port/out:
    config:
      dir: "internal/port/out/mocks"
    interfaces:
      Transcriber:
      Atomizer:
      NoteStore:
      TaxonomyLoader:
      Embedder:
      VectorIndex:
