package main

import (
	"fmt"
	"os"

	"github.com/aleksejmetlusko/second-brain/internal/config"
)

func main() {
	desc, err := config.Description()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("# .env.example — autogenerated by `make env-example`. Do not edit by hand.")
	fmt.Println(desc)
}
