// Command envexample generates a .env template from the Config struct tags.
package main

import (
	"fmt"
	"reflect"
	"strings"

	"github.com/aleksejmetlusko/second-brain/internal/config"
)

func main() {
	fmt.Println("# .env.example — autogenerated by `make env-example`. Do not edit by hand.")
	fmt.Println("# Copy to .env and fill in values for required entries.")
	fmt.Println()

	t := reflect.TypeOf(config.Config{})
	for i := range t.NumField() {
		f := t.Field(i)
		name := f.Tag.Get("env")
		if name == "" {
			continue
		}
		def := f.Tag.Get("env-default")
		required := f.Tag.Get("env-required") == "true"
		desc := f.Tag.Get("env-description")

		var notes []string
		if required {
			notes = append(notes, "required")
		}
		if def != "" {
			notes = append(notes, "default: "+def)
		}
		if desc != "" {
			fmt.Printf("# %s\n", desc)
		}
		if len(notes) > 0 {
			fmt.Printf("# (%s)\n", strings.Join(notes, ", "))
		}
		if strings.ContainsAny(def, " \t") {
			fmt.Printf("%s=%q\n", name, def)
		} else {
			fmt.Printf("%s=%s\n", name, def)
		}
		fmt.Println()
	}
}
