// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aleksejmetlusko/second-brain/internal/port/in"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIngestDumpUseCase creates a new instance of MockIngestDumpUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngestDumpUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngestDumpUseCase {
	mock := &MockIngestDumpUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIngestDumpUseCase is an autogenerated mock type for the IngestDumpUseCase type
type MockIngestDumpUseCase struct {
	mock.Mock
}

type MockIngestDumpUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngestDumpUseCase) EXPECT() *MockIngestDumpUseCase_Expecter {
	return &MockIngestDumpUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockIngestDumpUseCase
func (_mock *MockIngestDumpUseCase) Execute(ctx context.Context, req in.IngestRequest) (in.IngestResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 in.IngestResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, in.IngestRequest) (in.IngestResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, in.IngestRequest) in.IngestResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(in.IngestResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, in.IngestRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIngestDumpUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockIngestDumpUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req in.IngestRequest
func (_e *MockIngestDumpUseCase_Expecter) Execute(ctx interface{}, req interface{}) *MockIngestDumpUseCase_Execute_Call {
	return &MockIngestDumpUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *MockIngestDumpUseCase_Execute_Call) Run(run func(ctx context.Context, req in.IngestRequest)) *MockIngestDumpUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 in.IngestRequest
		if args[1] != nil {
			arg1 = args[1].(in.IngestRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIngestDumpUseCase_Execute_Call) Return(ingestResult in.IngestResult, err error) *MockIngestDumpUseCase_Execute_Call {
	_c.Call.Return(ingestResult, err)
	return _c
}

func (_c *MockIngestDumpUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, req in.IngestRequest) (in.IngestResult, error)) *MockIngestDumpUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
